### ISSUE TITLE
dba_qcfilter scarta tutte i context (livello, timerange) tranne uno.

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/libsim#1]
Il comando `dba_qcfilter` pare scartare tutte le var tranne quelle statiche (nome stazione, altezza, etc) e quelle relative ad un solo context.

Le prove sono effettuate con `libsim-6.1.0-1506`.

Ho committato il file di prova `dba_qcfilter-bug.bufr` nella directory `data` del branch `dba_qcfilter-bug-1`.

Il file di test (BUFR generico) contiene un solo messaggio con 4 context:
```
$ dbamsg dump --interpreted dba_qcfilter-bug.bufr
#0[0] generic message with 4 contexts:
Level 1,-,-,-  tr 1,0,3600  1 vars:
013011 TOTAL PRECIPITATION / TOTAL WATER EQUIVALENT(KG/M**2): 0.2
Level 1,-,-,-  tr 1,0,86400  1 vars:
013011 TOTAL PRECIPITATION / TOTAL WATER EQUIVALENT(KG/M**2): 7.4
Level 103,2000,-,-  tr 254,0,0  2 vars:
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 287.95
013003 RELATIVE HUMIDITY(%): 94
Level -,-,-,-  tr -,-,-  6 vars:
001019 LONG STATION OR SITE NAME(CCITTIA5): Camse
001194 [SIM] Report mnemonic(CCITTIA5): locali
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.60016
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.07738
007030 HEIGHT OF STATION GROUND ABOVE MEAN SEA LEVEL (SEE NOTE 3)(M): -1.0
007031 HEIGHT OF BAROMETER ABOVE MEAN SEA LEVEL (SEE NOTE 4)(M): 0.0
```
Filtrando con `dba_qcfilter`, viene scartata tutto tranne il context di anagrafica e uno degli altri 3:
```
$ dba_qcfilter < dba_qcfilter-bug.bufr | dbamsg dump --interpreted
#0[0] generic message with 2 contexts:
Level 103,2000,-,-  tr 254,0,0  2 vars:
012101 TEMPERATURE/DRY-BULB TEMPERATURE(K): 287.95
013003 RELATIVE HUMIDITY(%): 94
Level -,-,-,-  tr -,-,-  6 vars:
001019 LONG STATION OR SITE NAME(CCITTIA5): Camse
001194 [SIM] Report mnemonic(CCITTIA5): locali
005001 LATITUDE (HIGH ACCURACY)(DEGREE): 44.60016
006001 LONGITUDE (HIGH ACCURACY)(DEGREE): 12.07738
007030 HEIGHT OF STATION GROUND ABOVE MEAN SEA LEVEL (SEE NOTE 3)(M): -1.0
007031 HEIGHT OF BAROMETER ABOVE MEAN SEA LEVEL (SEE NOTE 4)(M): 0.0
```
Ho sospetto che nell'output mantenga solo l'ultimo dei context letti, sovrascrivendo i precedenti (con l'esclusione di quella di anagrafica).

**Comment by pat1** [comment]
riducendo la sequenza fortran a:

connection=dbaconnection(dsn="mem:")
sessionfrom=dbasession(connection,write=.true.,wipe=.true.)
call sessionfrom%messages_open_input(filename=input_file,mode="r",format="BUFR",simplified=.true.)
call sessionfrom%messages_open_output(filename=output_file,mode="w",format="BUFR")
do while (sessionfrom%messages_read_next())
  call sessionfrom%messages_write_next()
  call sessionfrom%remove_all()
end do
call sessionfrom%delete()

Si produce il seguqnte trace di chiamate alle api dballe fortran:

// ** Execution begins **
auto_ptr<DB> db0(DB::connect_from_url("mem:"));
DbAPI dbapi0(*db0, "write", "write", "write");
dbapi0.scopa();
dbapi0.messages_open_input("", "r", BUFR, true);
dbapi0.messages_open_output("", "w", BUFR);
ires = dbapi0.messages_read_next();
wassert(actual(ires) == 1);
dbapi0.messages_write_next("");
dbapi0.remove_all();
ires = dbapi0.messages_read_next();
wassert(actual(ires) == 0);
// dbapi0 not used anymore
trace.log (END)

che a mio parere denota un bug di dballe

**Comment by pat1** [comment]
E' la scusa in questo pezzo di codice che crea il problema:

  do i =1, size (metadata)

    ! here if metadata have some field missig they will be set to missing so it will be unset in dballe (I hope)
    call metadata(i)%dbaset(session)
    ier = idba_voglioquesto(session%sehandle, count)

    if (.not. c_e(count)) cycle
    do ii =1,count
      ier = idba_dammelo(session%sehandle, btable)
      !call session%var_related(btable)         !not needed after dammelo
      call session%scusa()
    end do

  end do

**Comment by pat1** [comment]
il problema era l'assenza di una unsetall prima dell'export:
call sessionfrom%unsetall()
call sessionfrom%messages_write_next()
