### ISSUE TITLE
problem calculating relative humidity from dewpoint temperature and t2m from ICON grib2 data

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#107]
given a source grib with t2m and dewpoint temperature:
```
vg6d_transform --output-variable-list=B13003 prou.grib u.grib
```
the resulting `u.grib` contains only missing data.

Source testa data: 
[prou.tar.gz](https://github.com/ARPA-SIMC/libsim/files/13472154/prou.tar.gz)

**Comment by dcesari** [comment]
The second field is a maximum temperature at the initial time (and strangely coded with some -999 "valid" values, we should check where it comes from), not an instantaneous temperature, so the timeranges do not match, it should probably not be used in general.

**Comment by dcesari** [comment]
Additional information: the -999 are on a tiny frame around the field border, it is probably a "feature" of the postprocessed fields, but that's a different problem.

**Comment by brancomat** [comment]
Thank you, this is an arkimap recipe issue that was provinding the wrong fields to libsim
