### ISSUE TITLE
Calcolo temperatura media da grib t2m

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#113]
Sto cercando di calcolare la temperatura media giornaliera a partire dai valori istantanei di t2m per i grib di IFS e ICON
(dati sorgenti di esempio: https://drive.google.com/drive/folders/1hNe-4TjgHM87rLBKNqBVznSDBFvsvnwG?usp=sharing)

Temo mi sfugga qualcosa di macroscopico nel come calcolarla:
```
$ arki-query --data "Reftime:=today 0:00; product: GRIB1,98,128,167 ; level: GRIB1,1;" http://arkiope.metarpa:8090/dataset/ifs_ita010 > ifs_ita010-t2m.grib
$ vg6d_transform --comp-stat-proc=0 --comp-step='1 00' --comp-frac-valid=0 ifs_ita010-t2m.grib ifs_ita010-tmed.grib
[stderr] WARN     vg6d_transform.volgrid6d_class.input_volume-vol1 - no timeranges of the desired statistical processing type 0 available

$ arki-query --data "Reftime:=today 0:00; product:GRIB2,,000,000,000,,; level:GRIB2S,103,000,0000000002; timerange:Timedef,,254," http://arkiope.metarpa:8090/dataset/icon_2I > icon_2I-t2m.grib
$ vg6d_transform --comp-stat-proc=0 --comp-step='1 00' --comp-frac-valid=0 icon_2I-t2m.grib icon_2I-tmed.grib 
[stderr] WARN     vg6d_transform.volgrid6d_class.input_volume-vol1 - no timeranges of the desired statistical processing type 0 available
```

**Comment by brancomat** [comment]
Mi rispondo parzialmente da solo, la sintassi corretta era:
```
vg6d_transform --comp-stat-proc=254:0 --comp-step='1 00' --comp-frac-valid=0 icon_2I-t2m.grib icon_2I-tmed.grib 
```

**Comment by dcesari** [comment]
La risposta è semplice, per fortuna, `--comp-stat-proc` accetta 2 parametri separati da `:`, il timerange "input" e il timerange "output", quindi se metti `--comp-stat-proc=254:0` funziona. `--comp-stat-proc=0` equivale a `--comp-stat-proc=0:0` (medie dalle medie). In generale sono possibili le combinazioni che hanno più o meno senso, ma non tutte.

**Comment by dcesari** [comment]
ah, scusa, sono arrivato lungo, non avevo neanche visto che c'ra già larisposta
