### ISSUE TITLE
Missing var B14198 from vargrib2bufr.csv

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/libsim#13]
Nella commit f50d919dce848ed7f2b7032abba115d56a60345d la var `B14198` è stata rimossa da `vargrib2bufr.csv`.

La suddetta var viene usata per generare il `GRIB` per il dataset `erg5` a partire dai dati dell'area agro:
* Conversione dei dati da `VM` (*Radiazione visibile media oraria componente dall'alto*, id Oracle`409`) a `BUFR (`var=B14198`, `level=1,-,-,-`, `trange=0,0,3600`)
* Conversione dei `BUFR` in `GRIB2` con `v7d_transform`

E' possibile reintrodurre tale var?

(Assegno il bug a @dcesari anche se sarebbe di Enrico Minguzzi, che non ha un account GitHub).

**Comment by dcesari** [comment]
On 10/02/2016 13:15, Emanuele Di Giacomo wrote:
> Nella commit f50d919
> <https://github.com/ARPA-SIMC/libsim/commit/f50d919dce848ed7f2b7032abba115d56a60345d>
> la var |B14198| è stata rimossa da |vargrib2bufr.csv|.
>
> La suddetta var viene usata per generare il |GRIB| per il dataset |erg5|
> a partire dai dati dell'area agro:
>
>   * Conversione dei dati da |VM| (/Radiazione visibile media oraria
>     componente dall'alto/, id Oracle|409|) a |BUFR
>     (|var=B14198|,|level=1,-,-,-|,|trange=0,0,3600`)
>   * Conversione dei |BUFR| in |GRIB2| con |v7d_transform|
>
> E' possibile reintrodurre tale var?

'zzarola (si può dire su github?)! immagino sia stata eliminata perché è 
stata rinvenuta la variabile standard WMO B14018 (v. stesso commit) con 
lo stesso significato. Non è possibile forzare (dbavm? erg5?) ad 
associare 14018 a oracleid 409? Sarebbe in ogni caso meglio non averle 
entrambe per la nota univocità delle variabili, ma chiederei anche 
conferma ad Enrico e altri esperti.

>
> (Assegno il bug a @dcesari <https://github.com/dcesari> anche se sarebbe
> di Enrico Minguzzi, che non ha un account GitHub).

**Comment by edigiacomo** [comment]
Nessun problema per passare da `B14198` a `B14018`.

Tuttavia, noto che con `B14198` (e libsim "vecchio") mi risultava il seguente product (`arki-scan --dump`):

```
Product: GRIB2(00200, 000, 004, 007, 004, 000)	# Downward short-wave radiation flux (W m-2)
```

Mentre ora:

```
Product: GRIB2(00200, 000, 200, 115, 004, 000)	# GRIB2(00200, 000, 200, 115, 004, 000)
```

I codici numerici sono, nell'ordine: `centre, discipline, category, number, table_version, local_table_version`

In particolare, mi perplime la category, che passa da 4 (*Short-wave Radiation*) a 200 (sconosciuto). Forse il problema è che non abbiamo le tabella aggiornate?

**Comment by dcesari** [comment]
On 10/02/2016 14:56, Emanuele Di Giacomo wrote:
> Nessun problema per passare da |B14198| a |B14018|.
>
> Tuttavia, noto che con |B14198| (e libsim "vecchio") mi risultava il
> seguente product (|arki-scan --dump|):
>
> |Product: GRIB2(00200, 000, 004, 007, 004, 000)  # Downward short-wave radiation flux (W m-2)
> |
>
> Mentre ora:
>
> |Product: GRIB2(00200, 000, 200, 115, 004, 000)  # GRIB2(00200, 000, 200, 115, 004, 000)
> |
>
> I codici numerici sono, nell'ordine: |centre, discipline, category,
> number, table_version, local_table_version|
>
> In particolare, mi perplime la category, che passa da 4 (/Short-wave
> Radiation/) a 200 (sconosciuto). Forse il problema è che non abbiamo le
> tabella aggiornate?

probabilmente è colpa del refuso della linea 186 (v. commit) che deve 
essere anch'essa convertita a 14018, e ti da il parametro standard 
grib2, però questo potrebbe far innervosire Enrico che si è inventato la 
tabella grib 200, lo contatto e vedo di fare la modifica.

**Comment by dcesari** [comment]
Riapro al issue perché ci sono pressioni a tornare alla 14198, tu Enrico ricordi perché avevi fatto quel commit? È corretta la mia interpretazione?

A occhio io direi che sono la stessa cosa nella nostra approssimazione

```
014018 INSTANTANEOUS SHORT-WAVE RADIATION (incoming)                    W/M**2
014198 Global (visible) irradiance (downward)                           W/M**2
```

In realtà differiscono nella codifica per il numero di bit, ma non ho verificato concretamente.
Che si fa? credo che sia comunque importante evotare duplicazione di variabili in vargrib2bufr e dballe.txt.
