### ISSUE TITLE
new dba url format in utils like v7d_transform not supported/documented

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/libsim#15]
https://github.com/ARPA-SIMC/dballe/issues/42

**Comment by brancomat** [comment]
(magari fa comodo, incollo da pagina wiki interna DballeImportazioneDati)

**SQLite**
```
   --dsn=sqlite:nomefile.sqlite
   --dsn=sqlite://nomefile.sqlite
```

**PostgreSQL**

```
   --dsn=postgresql://[[user][:password]@][host]/[dbname][?altri_parametri]
   # esempio pratico:
   --dsn=postgresql://test:test@radicchio/qc_test_pgsql
```

   La sintassi completa è definita qui:
   http://www.postgresql.org/docs/9.4/static/libpq-connect.html#AEN41094

**MySQL**

```
   --dsn=mysql://[host][:port]/[database][?propertyName1][=propertyValue1][&propertyName2][=propertyValue2]...
   # esempio pratico:
   --dsn=mysql://radicchio:3306/qc_test_mysql?user=test
```

   MySQL non ha una funzione per connettersi via URL, e dovendo
   implementare una sintassi di URL ci si è ispirati a questo:
   http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html

**Comment by dcesari** [comment]
grazie Branco, se non ci fossi tu...

**Comment by dcesari** [comment]
Paolo did you try the syntax (ARPA internal wiki http://www.smr.arpa.emr.it/simwiki/DballeImportazioneDati ):
```
# postgresql:
none/@postgresql://test:test@radicchio/qc_test_pgsql
# mysql:
none/@mysql://radicchio:3306/qc_test_mysql?user=test
# sqlite:
none/@sqlite:percentili.sqlite
```
does it work or not? In any case I agree that user/password@... syntax is obsolete without oracle and odbc, when the picture will be clear I will remove it and rewrite the help.

**Comment by pat1** [comment]
ho provato con mysql con username e password e non funziona.
Se oracle definiamo che sia obsoleto basta passare la url in modo trasparente.
Io sarei disposto a rimuovere user e password dalle API fortran 2003 di dballe:
```
type(dbaconnection) function dbaconnection_init(dsn, user, password,categoryappend,idbhandle)
```
poi per coerenza bisognerebbe rimuoverle dalle API fortran 77:
```
  ier=idba_presentati(handle,dsn,user,password)
```
e da vol7d:

```
SUBROUTINE vol7d_dballe_init(this,dsn,user,password,write,wipe,repinfo,&
 filename,format,file,categoryappend,time_definition,idbhandle,template)
```
rimuovendo magari la vecchia interfaccia:
```
SUBROUTINE vol7d_dballe_import_old(this, var, network, coordmin, coordmax, timei, timef,level,timerange, set_network,&
 attr,anavar,anaattr, varkind,attrkind,anavarkind,anaattrkind,anaonly,dataonly,ana)
```

**Comment by pat1** [comment]
mi correggo:
questa sintassi non l'ho provata:
```
# mysql:
none/@mysql://radicchio:3306/qc_test_mysql?user=test
```
ma se devo dire che mi piace la risposta è no

**Comment by dcesari** [comment]
La mia proposta è di rimuovere la necessità di "none/@" all'inizio che è obsoleta, se tu riesci a verificare che `none/@mysql://radicchio:3306/qc_test_mysql?user=test` funziona, poi posso procedere alla rimozione di none/@ all'inizio che non richiedo strettamente un cambio di api, basta non passare user e password. Dopo questo saremmo allineati tra libsim e dbadb.

**Comment by pat1** [comment]
```
v7d_transform --input-format=dba "none/@mysql:///db?user=mioutente&password=bracadabra" tmp.v7d
```
con questa sintassi pare funzionare

**Comment by dcesari** [comment]
Ho fatto un commit che distingue meglio che può i casi user/password@dsn dai casi dsn=URI salvando capra e cavoli. quinid non è più necessario aggiungere "none/@". Quando poi elimineremo definitivamente anche lato libsim odbc con user/password separati si potrà semplificare tutto. Pregasi provare.
