### ISSUE TITLE
make check fallito su char_utilities_test

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#29]
Su richiesta di Paolo ho riabilitato il make check in libsim (che è cosa buona e giusta) ma fallisce.

questo l'output di test-suite.log:

```
========================================
   libsim 6.1.11: base/test-suite.log
========================================

# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: char_utilities_test
=========================

 === Testing char_utilities module ===
 Checking int_to_char
 Checking byte_to_char
 Checking real_to_char
 Checking double_to_char
 Checking l_nblnk
 Checking l_nblnk degenerated
 Checking f_nblnk
 Checking f_nblnk degenerated
FAIL char_utilities_test (exit status: 1)
```

**Comment by pat1** [comment]
Non riesco a riprodurre, forse bisogna utilizzare alcune opzioni di compilazione? 

./char_utilities_test 
 === Testing char_utilities module ===
 Checking int_to_char
 Checking byte_to_char
 Checking real_to_char
 Checking double_to_char
 Checking l_nblnk
 Checking l_nblnk degenerated
 Checking f_nblnk
 Checking f_nblnk degenerated
 Checking align_center even
 Checking align_center odd
 Checking align_center degenerated
 Checking word_split - 3 words
 Checking word_split degenerated - 1 word
 Checking word_split degenerated - 0 words
 Checking word_split with indices - 3 words
 Checking word_split with indices - 3 words - checking indices
 Checking line_split
 checking wash_char

**Comment by dcesari** [comment]
Sembra dovuta ad un'ottimizzazione (per me sbagliata) di gfortran nel codice del programma test, il seguente codice
```
PRINT*,f_nblnk('    ')
PRINT*,f_nblnk('')
PRINT*,f_nblnk('    ') + f_nblnk('')
```
compilato con -O2 da questo risultato:
```
           5
           1
           2
```
cioè nella terza riga gfortran sembra credere che la stessa funzione sia chiamata 2 volte con lo stesso argomento e la chiama una volta solo riciclando il risultato, il problema è che in realtà '    ' è diverso da ''; con -O0 invece il risultato è questo (giusto):
```
           5
           1
           6
```
Probabilmente i test li abbiamo sempre fatti in modalità sviluppo senza ottimizzazioni, e non ce ne siamo mai accorti, modifico il test.

**Comment by dcesari** [comment]
Test sistemato
