### ISSUE TITLE
add command line parameter to v7d_qccli v7v 7d_qcspa v7d_qctem

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/libsim#3]
eliminare la namelist e utilizzare i parametri a linea di comando

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
