### ISSUE TITLE
[v7d_transform] allocazione di memoria pesante

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#35]
Ho un db sqlite con precipitazioni cumulate orarie (che allego: [ipf.zip](https://github.com/ARPA-SIMC/libsim/files/879119/ipf.zip)) dal quale vengono fatte una serie di cumulate a 90-60-30-15-5 giorni con questa sintassi (con `comp-step` che varia a seconda dei casi):

```
v7d_transform --input-format=dba --output-format=csv --comp-stat-proc 1 --comp-step="90 00"  --comp-start="2016-12-29" --csv-header=1 --comp-frac-valid="0.6" "sqlite:/idro_preci_frane.sqlite"  preci_cumulata_90.CSV
```

Al di là dei tempi (già oggetto di analisi altrove) al momento il problema è l'allocazione di memoria: lanciandolo dentro a `/usr/bin/time -v` salta fuori un:
```
Maximum resident set size (kbytes): 2124580
```
quindi ha dei picchi di allocazione di 2Gb per dei calcoli che non parrebbero probitivi (la cosa è indipendente dal variare di `comp-step`). E' possibile migliorare/mitigare la situazione?

**Comment by dcesari** [comment]
Aggiungendo l'argomento `--set-network=generic` tutti i dati vengono appiattiti in una sola rete e l'occupazione di memoria si riduce ad 1/3 circa, e anche i tempi di elaborazione migliorano.

Per il caso proposto il risultato non cambia tranne che nella colonna network in cui, ovviamente, scompare l'informazione della rete, che comunque si conserva nella variabile B01194. Per verificare più comodamente con un diff che il risultato non cambia, si può usare l'argomento `--csv-column=time,timerange,ana,level` con e senza `--set-network` che esclude la colonna diversa.

**Comment by brancomat** [comment]
Grazie della dritta, aggiunta opzione, confermo riduzione dell'occupazione, 700Gb non è comunque poco ma molto meglio di prima, chiudo il bug.

**Comment by dcesari** [comment]
Lavorando un po' con valgrind seguendo questa [discussione](http://stackoverflow.com/questions/131303/how-to-measure-actual-memory-usage-of-an-application-or-process) ho inserito un'ottimizzazione nel codice v7d-dballe nel caso in cui non applichi filtri in importazione, nel presente caso riduce il picco di un 100MB. Al prossimo push.
