### ISSUE TITLE
error in a program that reads raingauges data and attributes from dballe and writes them to a text file

### ISSUE THREAD

**Issue by annafornasiero** [ARPA-SIMC/libsim#36]
In the module preci_anagrafica_stazioni_class.f90 a segmentation fault error is produced when trying to assign the index of the staz code attribute to the var indstazid.
I have attached the programs and the data into set_prove.tar.gz.

[set_prove.tar.gz](https://github.com/ARPA-SIMC/libsim/files/912909/set_prove.tar.gz)

The error:

Program received signal SIGSEGV, Segmentation fault.
__memcmp_ssse3 () at ../sysdeps/x86_64/multiarch/memcmp-ssse3.S:1862
1862            movl    -10(%rdi), %eax
Missing separate debuginfos, use: dnf debuginfo-install SuperLU-5.2.0-1.fc24.x86_64 armadillo-7.800.2-1.fc24.x86_64 arpack-3.3.0-2.b0f7a60git.fc24.x86_64 atlas-3.10.2-12.fc24.x86_64 blas-3.6.1-1.fc24.x86_64 bzip2-libs-1.0.6-21.fc24.x86_64 cfitsio-3.370-6.fc24.x86_64 expat-2.1.1-2.fc24.x86_64 fontconfig-2.11.94-7.fc24.x86_64 fortrangis-2.6-1.x86_64 freetype-2.6.3-3.fc24.x86_64 freexl-1.0.2-3.fc24.x86_64 gdal-libs-2.0.2-6.fc24.x86_64 giflib-4.1.6-15.fc24.x86_64 jasper-libs-1.900.13-3.fc24.x86_64 jbigkit-libs-2.1-5.fc24.x86_64 lapack-3.6.1-1.fc24.x86_64 lcms2-2.8-2.fc24.x86_64 libICE-1.0.9-8.fc24.x86_64 libSM-1.2.2-4.fc24.x86_64 libX11-1.6.3-3.fc24.x86_64 libXau-1.0.8-6.fc24.x86_64 libaio-0.3.110-6.fc24.x86_64 libbsd-0.8.3-1.fc24.x86_64 libdap-3.17.2-1.fc24.x86_64 libgeotiff-1.4.0-7.fc24.x86_64 libgta-1.0.7-3.fc24.x86_64 libsim-6.1.15-1.x86_64 libspatialite-4.3.0a-2.fc24.x86_64 libtiff-4.0.7-2.fc24.x86_64 libtool-ltdl-2.4.6-13.fc24.x86_64 libuuid-2.28.2-2.fc24.x86_64 libwebp-0.5.2-1.fc24.x86_64 libxcb-1.11.1-2.fc24.x86_64 libxml2-2.9.3-3.fc24.x86_64 log4c-1.2.4-8.fc24.x86_64 lua-libs-5.3.4-1.fc24.x86_64 mariadb-libs-10.1.21-3.fc24.x86_64 netcdf-fortran-4.4.3-2.fc24.x86_64 nss-3.29.3-1.0.fc24.x86_64 nss-softokn-freebl-3.29.3-1.0.fc24.x86_64 nss-util-3.29.3-1.0.fc24.x86_64 ogdi-3.2.0-0.26.beta2.fc24.x86_64 openblas-openmp-0.2.19-4.fc24.x86_64 openjpeg2-2.1.2-3.fc24.x86_64 openssl-libs-1.0.2k-1.fc24.x86_64 pcre-8.40-5.fc24.x86_64 poppler-0.41.0-3.fc24.x86_64 proj-4.9.2-2.fc24.x86_64 shapelib-1.3.0f-9.fc24.x86_64 unixODBC-2.3.4-2.fc24.x86_64 xerces-c-3.1.4-1.fc24.x86_64 xz-libs-5.2.2-2.fc24.x86_64
(gdb) where
#0  __memcmp_ssse3 () at ../sysdeps/x86_64/multiarch/memcmp-ssse3.S:1862
#1  0x00007ffff7a6a99e in __vol7d_var_class_MOD_vol7d_var_eq () from /lib64/libsim_vol7d.so.6
#2  0x00007ffff7a6acfa in __vol7d_var_class_MOD_index_var () from /lib64/libsim_vol7d.so.6
#3  0x000000000040a04e in preci_anagrafica_stazioni_class::scrivi_preci_stazioni_tab_txt (
    this=<**error reading variable: value requires 490227048 bytes, which is more than max-value-size**>, giornaliere=.FALSE.)
    at preci_anagrafica_stazioni_class.f90:351
#4  0x00000000004030f3 in leggi_preci_da_oracle_e_scrivi_file () at leggi_preci_da_dballe_e_scrivi_file.f90:186
#5  0x00000000004020bd in main (argc=argc@entry=1, argv=0x7fffffffe260) at leggi_preci_da_dballe_e_scrivi_file.f90:18
#6  0x00007ffff6567731 in __libc_start_main (main=0x4020a0 <main>, argc=1, argv=0x7fffffffdf38, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdf28) at ../csu/libc-start.c:289
#7  0x00000000004020f9 in _start ()

**Comment by dcesari** [comment]
The problem was in the user program, now fixed
