### ISSUE TITLE
Extend variable table with center 80

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/libsim#38]
BUFR-GRIB variable table file `vargrib2bufr.csv` should be extended to contain COSMO-specific and some ECMWF-specific grib1 entries also for centre 80, Italy. A (python?) program could be a good way to do this.

**Comment by edigiacomo** [comment]
Mi offro anche di darti una mano se posso accelerare la cosa, perché è bloccante per il passaggio a COSMO-i5.

**Comment by dcesari** [comment]
La mia idea era fare uno script python per mantenere vargrib2bufr.csv, con operazioni varie associate a opzioni a linea di comando. La cosa da fare adesso sarebbe banalmente duplicare le righe con x1,x2,x3,200,201,x,255,x4,x5 in x1,x2,x3,80,201,x,255,x4,x5.
