### ISSUE TITLE
[v7d_transform] comp-start modificata automaticamente quando mancano dati

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#50]
Questo potrebbe essere sia un bug che una roba da RTFM, temporaneamente la etichetto sia come question che come bug visto che blocca alcuni lavori.

Tema: aggregazione di max/min da istantanee su dati previsti.
Per calcolare le Tmin della corsa 2017-02-15 00:00 su intervallo 6-6 partendo dalle istantanee, faccio una cosa tipo:
```
v7d_transform --input-format=dba --time-definition=0 --comp-stat-proc=254:3 --comp-step='1 00' --comp-start="2018-02-15 06:00" --set-network=cosmoi7 --output-format=dba --variable-list=B12101 --comp-frac-valid=0 none/@sqlite:/dev/shm/tmp.sqlite none/@sqlite:/dev/shm/kalman.sqlite
```
(e funziona).

Per la Tmax per la stessa corsa avrei esigenza di partire prima dei dati effettivamente disponibili in modo da avere la Tmax alla +18 (mancherebbero i dati dalle 18 alle 00 ma è ritenuto accettabile).

Ho tentato un:
```
v7d_transform --input-format=dba --time-definition=0 --comp-stat-proc=254:2 --comp-step='1 00' --comp-start="2018-02-14 18:00" --set-network=cosmoi7 --output-format=dba --variable-list=B12101 --comp-frac-valid=0 none/@sqlite:/dev/shm/tmp.sqlite none/@sqlite:/dev/shm/kalman.sqlite
```
Ma si comporta come se avessi impostato `comp-start="2018-02-15 00:00"` e calcola la Tmax su intervallo 0-24. Se invece parto dalle 18 del giorno successivo funziona (ma mi manca un dato, che vorrei).
Uso l'opzione sbagliata?

(il db di partenza è in allegato : [tmp.zip](https://github.com/ARPA-SIMC/libsim/files/1727472/tmp.zip) )

**Comment by dcesari** [comment]
Probabilmente da qualche parte c'è un'operazione tipo max(tmin dei dati, comp-start) se non ci sono rischi di sorta posso pensare di eliminare questa operazione. Controllo.

**Comment by dcesari** [comment]
Avrei sistemato, per il momento chiedo di provare via `/net/malina/scratch/dcesari/github/libsim/bin/v7d_transform`. Funziona ma genera dei bufr "previsti" con P2>P1:
```
004192 [SIM] Time range type(NUMERIC): 2
004193 [SIM] Time range P1(NUMERIC): 64800
004194 [SIM] Time range P2(NUMERIC): 86400
```
cioè la cui elaborazione comincia prima dell'inizio della previsione, non so se questo può mandare in crisi qualche parte della filiera dballe & c.. In realtà il problema sorge solo se uno usa `--comp-start`< data minima in input, quindi è circoscrivibile. Cmq prima di fare un commit in master aspetto qualche eventuale reazione.

**Comment by brancomat** [comment]
Confermo, funziona!
