### ISSUE TITLE
[v7d_transform] errore su estrazione attributi

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#51]
Ho un db dballe sqlite con le seguenti variabile specificate come attributi in una particolare network: B33201, B33202, B33203, B33204, B33205, B33206, B33207, B33208 (legate al filtro di kalman)

su `provami-qt` vedo tutto correttamente, il problema avviene in estrazione:
```
$ dbadb wipe --dsn=sqlite:///dev/shm/out.sqlite
$ export LOG4C_PRIORITY=debug
$ v7d_transform --input-format=dba --output-format=dba --network-list=kalman-cosmoi7 --variable-list="B12101" --attribute-list="B33207,B33208" --start-date="2018-02-14 06:00" --end-date="2018-02-14 06:00" sqlite:/dev/shm/kalman.sqlite sqlite:/dev/shm/out.sqlite
[stderr] DEBUG    v7d_transform.vol7d_dballe_class - start import vol7d_dballe
[stderr] DEBUG    v7d_transform.vol7d_dballe_class - start import vol7d_dballe ingest for constant station data
[stderr] DEBUG    v7d_transform.vol7d_dballe_class - end import vol7d_dballe ingest
[stderr] DEBUG    v7d_transform.vol7d_dballe_class - start import vol7d_dballe dba2v7d
[stderr] DEBUG    v7d_transform.vol7d_dballe_class - end import vol7d_dballe dba2v7d
[stderr] DEBUG    v7d_transform.vol7d_dballe_class - start import vol7d_dballe ingest for station data
[stderr] ERROR    v7d_transform.dballe_class - QC value names must start with '*'
[stderr] ERROR    v7d_transform.dballe_class - 
[stderr] INFO     v7d_transform.dballe_class - 
Fatal error: dballe: QC value names must start with '*'
```

secondo la manpage:
> if attribute-list is not provided all  present  attributes  in  input  will  be  imported

ho provato quindi a dare lo stesso comando omettendo `attribute-list`, aspettandomi di ritrovare tutti gli attributi nel nuovo db ma (sempre guardandoci con `provami-qt`) li perdo tutti. Sembra che per libsim non siano attributi (se ha senso).

Il db originale è troppo pasciuto per allegarlo, si trova al momento su `/autofs/scratch2/dbranchini/kalman.sqlite`

**Comment by pat1** [comment]
come dice il messaggio di errore le variabili di attributo devono avere un prefisso "*":
v7d_transform --input-format=dba --output-format=dba --network-list=kalman-cosmoi7 --variable-list="B12101" --attribute-list="*B33207,*B33208" --start-date="2018-02-14 06:00" --end-date="2018-02-14 06:00" sqlite:kalman.sqlite sqlite:/dev/shm/out.sqlite

Nel secondo caso se si vogliono usare gli attributi in modo trasparenete e non nella modalità "quality control" che è il dafault deve essere specificata l'opzione --disable-qc : 
v7d_transform --input-format=dba --output-format=dba --network-list=kalman-cosmoi7 --variable-list="B12101" --start-date="2018-02-14 06:00" --disable-qc --end-date="2018-02-14 06:00" sqlite:kalman.sqlite sqlite:/dev/shm/out.sqlite

In questo caso specifico trattandosi di kalman consiglio l'uso di --disable-qc comunque e ovunque

**Comment by brancomat** [comment]
Grazie, così funziona
