### ISSUE TITLE
eccodes support

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#52]
The current `configure.ac` [looks explicitely for `grib_api`](https://github.com/ARPA-SIMC/libsim/blob/master/configure.ac#L302-L320)

It should consider `eccodes` too, [as arkimet already does](https://github.com/ARPA-SIMC/arkimet/blob/master/configure.ac#L201-L235).

(I'm not sure of the implications, will that suffice?)

**Comment by brancomat** [comment]
Almost everything works as expected supporting both grib_api and eccodes BUT there's an issue in libsim.pc.in:
https://github.com/ARPA-SIMC/libsim/blob/master/libsim.pc.in#L13
```
Requires.private: log4c gdal libdballef grib_api_f90 netcdf-fortran
```
This generate a conflict (requires grib_api as a dependency of `libsim-devel` even when compiled with eccodes)

`grib_api_f90` should be dynamically changed to `eccodes_f90` when eccodes is detected. But I'm not sure how to do it.

**Comment by edigiacomo** [comment]
I'm testing a patch.

**Comment by edigiacomo** [comment]
Commit f0f98be should fix the problem.

**Comment by edigiacomo** [comment]
The fix should work. From https://api.travis-ci.org/v3/job/428049075/log.txt:
```
Provides: libsim-devel = 6.2.8-1 libsim-devel(x86-64) = 6.2.8-1 libtool(/usr/lib64/liblog4fortran.la) libtool(/usr/lib64/libsim_alchimia.la) libtool(/usr/lib64/libsim_base.la) libtool(/usr/lib64/libsim_graphics.la) libtool(/usr/lib64/libsim_qc.la) libtool(/usr/lib64/libsim_termolib.la) libtool(/usr/lib64/libsim_vol7d.la) libtool(/usr/lib64/libsim_volgrid6d.la) pkgconfig(libsim) = 6.2.8
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: /usr/bin/pkg-config liblog4fortran.so.6()(64bit) libsim_alchimia.so.6()(64bit) libsim_base.so.6()(64bit) libsim_graphics.so.6()(64bit) libsim_qc.so.6()(64bit) libsim_termolib.so.6()(64bit) libsim_vol7d.so.6()(64bit) libsim_volgrid6d.so.6()(64bit) pkgconfig(eccodes_f90) pkgconfig(gdal) pkgconfig(libdballef) pkgconfig(log4c) pkgconfig(netcdf-fortran)
```
