### ISSUE TITLE
output-format='BUFR:generic-frag' non supported

### ISSUE THREAD

**Issue by amontani** [ARPA-SIMC/libsim#53]
Dear all,
  I use  libsim-6.2.5-1.x86_64

I have just tried the following command 
v7d_transform --disable-qc  --input-format='BUFR' --output-format='BUFR:generic-frag' oss_nc_2703_2505 out.bfr
and I get the following message:
[stderr] ERROR    v7d_transform.dballe_class - requested export template generic-frag which does not exist
[stderr] ERROR    v7d_transform.dballe_class - 
Fatal error: dballe: requested export template generic-frag which does not exist

According to man page, this output format is supported:
--output-format=STRING
         format of output file, in the form 'name[:template]'; 'native' for vol7d native binary format (no template to be specified); 'BUFR' and 'CREX' for corresponding formats, with template as an alias like
'synop', 'metar', 'temp', 'generic', empty for 'generic', the special value 'generic-frag' is used to generate bufr on file where ana data is reported only once at beginning and data in other bufr after;

**Comment by pat1** [comment]
Can you remember us the use case of this option?
generic-frag was lost in new dballe implementation in libsim

**Comment by pat1** [comment]
you can use this command to get ana only file in native format:
v7d_transform --input-format BUFR  --variable-list=""  prec.bufr prec.v7d
and you can use prec.v7d in vg6d_getpoint.

This do not work for bufr format as is not possible to write ana only in generic template.
