### ISSUE TITLE
Implement dballe optimisation query=attrs

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/libsim#59]
Since https://github.com/ARPA-SIMC/dballe/issues/117 we can set `attrs` as a query key to speed up dballe queries that want attributes, likely in vol7d_dballe_class.F03 around l. 352:
```
+IF (c_e(query)) THEN
+! IF (LEN_TRIM(qury) > 0) THEN...  
+  query = TRIM(query)//',attrs'
+ELSE
+  query = 'attrs'
+ENDIF
```
and 552:
```
-  myfilter=dbafilter(filter=filter,contextana=.TRUE.,query=cmiss)
+  myfilter=dbafilter(filter=filter,contextana=.TRUE.,query='attrs')
```

**Comment by dcesari** [comment]
Or in dballe_class.F03 around 2318 (dbafilter_init) depending on (ana)starvar?

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
