### ISSUE TITLE
Where and what is config.h file?

### ISSUE THREAD

**Issue by Beliavsky** [ARPA-SIMC/libsim#60]
I am trying to compile some sources manually. The command

gfortran -c kinds.f90

gives output

kinds.f90:18:2:

 #include "config.h"
  1
Warning: Illegal preprocessor directive

I can translate this line to 

INCLUDE "config.h"

but I need a config.h file.

**Comment by pat1** [comment]
config.h is created by ./configure procedure.
You can try to create manually this file but we cannot provide support about this.
config .h have a lot of #define 
here only a little example:
```
/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if building universal (internal helper macro) */
/* #undef AC_APPLE_UNIVERSAL_BUILD */

/* Enable alchimia code */
/* #undef ALCHIMIA */

/* Enable debugging mode */
/* #undef DEBUG */

/* Disable some elemental functions on xlf */
#define ELEMENTAL_UNLESSXLF ELEMENTAL

/* Enable major part of F2003 features (gfortran 4.8) */
#define F2003_EXTENDED_FEATURES 1

/* Enable some F2003 features (gfortran 4.6) */
#define F2003_FEATURES 1

/* Enable full F2003 features (gfortran 4.9) */
/* #undef F2003_FULL_FEATURES */
```
