### ISSUE TITLE
Evapotraspirazione secondo Penman-Monteith in varbufr2vargrib.csv

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/libsim#62]
Si dovrebbe aggiungere l'evapotraspirazione di riferimento giornaliera e oraria secondo Penman-Monteith, necessaria per ERG5:

| LEVEL        | TRANGE    | VAR    |
|--------------|-----------|--------|
| 103,2000,-,- | 1,0,3600  | B13232 |
| 103,2000,-,- | 1,0,86400 | B13232 |

**Comment by dcesari** [comment]
Assegno a 200,0,193,2 (fino ad ora avevamo definito come var. locali in grib2 solo 200,0,192,2 Leaf wetness duration, sempre per erg5)
