### ISSUE TITLE
Is v7d_transform suitable for converting a stream of BUFR data to GeoJSON?

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/libsim#68]
I'd like to delete the `bufr2json` package because:

1. The conversion to dballe JSON was obsoleted by `dbamsg dump --json`
2. The conversion to GeoJSON could be obsoleted by `v7d_transform --output-format=geojson`

However, `bufr2json` is frequently used in pipe (e.g. in `arkimet-postprocessor-suite`) and I don't know the memory usage of `v7d_transform` with a large stream of input data: it reads up to the end and then write the GeoJSON? Or it writes one BUFR at a time?

**Comment by pat1** [comment]
v7d_transform reads up to the end and then write the GeoJSON and memorize all the data in a big matrix that can have a lot of unused location. As example it cannot manage a lot of temp with level different each to other. It cannot be used as general purpose tools in pipe.
Is possible to write a tools with dballe fortran 2003 api (not v7d).

**Comment by pat1** [comment]
v7d_transform reads up to the end and then write the GeoJSON and memorize all the data in a big matrix that can have a lot of unused location. As example it cannot manage a lot of temp with level different each to other. It cannot be used as general purpose tools in pipe.
Is possible to write a tools with dballe fortran 2003 api (not v7d).

**Comment by edigiacomo** [comment]
Thanks, then there's no reason to delete https://github.com/ARPA-SIMC/bufr2json.
