### ISSUE TITLE
Support difference (pindicator=4) in v7d_transform comp-stat-proc

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/libsim#74]
I don't know if it's possible but I'd like to e.g. compute the daily difference between maximum daily temperature. Something like:

```
v7d_transform \
    --variable-list=B12101 \
    --timerange=2,0,86400  \
    --comp-step='1 00' \
    --comp-stat-proc='2:4' \
    ...
```

**Comment by dcesari** [comment]
Actually statistical processing on time range 4 is implemented, but it is probably not exactly what you need. It is interpreted as the difference between the value at the end and the value at the start of the interval (as WMO says). It can be computed from timerange 254 or 4, with some ascii art, where a,b,c,etc are the instantaneous values:

```
Time 0___3___6___9__12__15

254  a___b___c___d___e___f
--comp-stat-proc=254:4 --comp-step='0 03'
4:3  |b-a|c-b|d-c|e-d|f-e|
--comp-stat-proc=4:4 --comp-step='0 06'
4:6  |  c-a  |  e-c  |

same result in one step:
254  a___b___c___d___e___f
--comp-stat-proc=254:4 --comp-step='0 06'
4:6  |  c-a  |  e-c  |
```
So from max/min it does not work, we have to think how to adapt it to your case (anyway all never tested).

**Comment by edigiacomo** [comment]
Thank you Davide for the nice art :) However, I don't understand why it can be computed from time range 4 (that, if I understand correctly, is defined in an interval) and not from any another timerange defined in an interval (e.g maximux, minimum, etc).

Or maybe it should be represented as:

```
254  a_____b______c______d______e______f
--comp-stat-proc=254:4 --comp-step='0 03'
4:3  __(b-a)__(c-b)__(d-c)__(e-d)__(f-e)
```

In other words, the timerange 4 is an instantaneous value too?

I definitely know that there's some reason that I'm missing, then I see only two solutions: (1) defining a new timerange and a new implementation in libsim or (2) "cheating" libsim and changing the timerange of the input data to 254.

P.S. I've tried to process the timerange 4 from 254 to understand how p1 and p2 are set, but I have the following problems:
- Segfault under fedora 28 (v6.3.1)
- Segfault under fedora 30 (v6.4.0-1)
- Empty file under f24 (v6.3.1)

I'll open a new issue for this problem.

**Comment by dcesari** [comment]
You should first convert the maximum values back to (pseudo)instantaneous values at the centre of the interval using the inverse transformation (`--comp-stat-proc='2:254'`) then compute differences based on instantaneous values (`--comp-stat-proc='254:4'`) which is supported.
