### ISSUE TITLE
Compilation error with configure flag --enable-f2003-full-features

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/libsim#78]
Se abilito --enable-f2003-full-features in fase di configure ottengo una serie di errori in compilazione su Fedora 30
```
dballe_class.F03:4388:33:

 4388 | call session%memconnection%delete()
      |                                 1
Error: ‘delete’ at (1) is not a member of the ‘dbaconnection’ structure
dballe_class.F03:3813:38:

 3813 | subroutine dbaconnection_delete(handle)
      |                                      1
Error: Argument of FINAL procedure at (1) must be of type ‘dbaconnection’
dballe_class.F03:4379:36:

 4379 | subroutine dbasession_delete(session)
      |                                    1
Error: Argument of FINAL procedure at (1) must be of type ‘dbasession’
```

**Comment by pat1** [comment]
il supporto per FINAL nel modulo dballe era stato abbozzato; l'evoluzione del compilatore evidentemente ha evidenziato problemi.
Ho risolto i problemi di compilazione nel mio checkout, ma i test poi falliscono.
Bisognerebbe fare un po' di analisi di come si comporta nella realtà il compilatore perchè pare che la funzione final in realtà non venga chiamata quando mi aspetterei che lo fosse ...
Dipende dall'urgenza (che mi pare sia alta) ; possiamo disabilitare i final nel modulo dballe anche con 
--enable-f2003-full-features attivato

**Comment by dcesari** [comment]
L'urgenza era legata al voler usare di f2003-full-features per includere un pezzo di codice che usa il modulo intrinseco `ieee_arithmetic` (non disponibile sulle versioni di gfortran che usiamo con enable-2003-features) per fare controlli sui NaN (dataset geotiff DPC). In realtà ho trovato un escamotage per fare il controllo anche senza ieee_arithmetic per cui al momento non è più urgente.
Però non lascerei codice che non compila neanche sull'ultima fedora e/o che fa affidamento su un'implementazione incerta di certe features in gfortran.

**Comment by dcesari** [comment]
Teniamo così in attesa che i finalizzatori funzionino.
