### ISSUE TITLE
negative precipitations in accumulation

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#79]
in short:
 ```
$ arki-query --data 'Reftime:=today 0:00; Product: GRIB1,80,2,61; level:g00' http://arkiope.metarpa:8090/dataset/cosmo_5M_ita > /tmp/tp.grib
$ grib_dump /tmp/tp.grib|grep minimum|sort -u
  #-READ ONLY- minimum = 0;
$ vg6d_transform --comp-stat-proc=1 --comp-step='0 06' --comp-full-steps /tmp/tp.grib /tmp/tp6.grib
grib_dump /tmp/tp6.grib|grep minimum|sort -u
  #-READ ONLY- minimum = 0;
  #-READ ONLY- minimum = -0.000244141;
  #-READ ONLY- minimum = -15.5176;
```

this is particularly infingardo because subsequent libsim processing generate a  error for `outside the range [-0.1,1638.1] for B13011 (TOTAL PRECIPITATION / TOTAL WATER EQUIVALENT)`

**Comment by dcesari** [comment]
Ho dimenticato di commentare: -15. kg/m2 mi pare un errore grossolano dei grib (tipo corsa principale e backup mischiate), ciò non toglie che precipitazioni <0 possono comparire per problemi di troncamento nel grib, ed è difficile stabilire a priori quale può essere l'ordine di grandezza massimo (nella fattispecie < -0.1 o meno). Essendo la cumulazione agnostica del parametro, si potrebbe forse introdurre un argomento che dice che i dati elaborati devono essere >=0. Da studiare.

**Comment by dcesari** [comment]
Con il commit 4fc708ce8268b7eead708a613e8cd7311d788b1e, nei casi di cumulazione per differenze di campi grigliati che devono essere fisicamente positivi (secondo la nuova tabella `varbufr.csv`) i valori <0 vengono troncati. Si può eventualmente allargare ad altri casi.
