### ISSUE TITLE
[vg6d_transform] calcolo temperature massime e minime da t2metri per dati previsti

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#8]
Attualmente è possibile aggregare tmax e tmin già calcolare tipo ad esempio
     vg6d_transform --comp-stat-proc=[2|3] --comp-step='1 00' --comp-full-steps in.grib out.grib

Sarebbe forse interessante implementarne il calcolo direttamente dalla t2m per i modelli che escono senza quel tipo di variabile (tipo cosmo 2.8)
A monte c'è qualche problema di specifiche però sul calcolo della tmin, a differenza dello 0-24 della tmax ho visto implementazioni 9-9, 18-06, 12-12...

**Comment by dcesari** [comment]
On 13/01/2016 13:57, Daniele Branchini wrote:
> Attualmente è possibile aggregare tmax e tmin già calcolare tipo ad esempio
> vg6d_transform --comp-stat-proc=[2|3] --comp-step='1 00'
> --comp-full-steps ingrib outgrib

ci sarebbe il calcolo di max e min dalle istantanee e.g. 
--comp-stat-proc=254:2 ma se non ricordo male è implementato solo per 
dati su punti sparsi con timerange analisi/osservazione.

C'è un po di skizofrenia purtroppo nel comp-stat-proc, da migliorare...

**Comment by brancomat** [comment]
Separo due problemi legati alla stessa issue per un chiarimentino, che al momento le mie esigenze sarebbero:

1. tmax e tmin da t2m (e eventualmente umax e umin) per dati grigliati (quindi `vg6d_transform`)
 (e questo ho capito che sarebbe da implementare)

2. _arrivare_ a tmax e tmin su punti sparsi partendo da t2m grib prevista

qui con @pat1 ci chiedevamo: se estraggo su punti sparsi con `vg6d_transform` e opzione `--time-definition=1` i file v7d (o bufr) risultanti posso calcolarli via `v7d_transform --comp-stat-proc=254:2`? O il commento su timerange analisi/osservazione vuol dire che discrimina sul p2?

**Comment by dcesari** [comment]
mmmh, mi pare che la risposta alla 2 sia purtroppo negativa, nel senso che anche --time-definition=1, pur modificando il reftime, non tocca il timerange, cioè non trasforma previsioni in osservazioni quindi p1 (non p2) resta >0, per cui ci vorrebbe un filtro intermedio tipo grib_set che lo mette a zero. Sarebbe meglio intervenire alla radice e implementare il calcolo.

**Comment by brancomat** [comment]
Aggiungo il tag devel blocking e aggiungo @pat1 agli assegnatari perché il calcolo di massimi e minimi di temperatura e umidità relativa da previsti e osservati 6-18 e 18-6 tramite libsim è lo step 0 per migrare le procedure relative a filtro di kalman e praticamente ci sono un server oracle e un server fedora 12 su solo per quelle.

In alternativa possiamo riscrivere / fare porting del calcolo in altri sistemi ma sarebbe moooolto più pulito/standard averlo in libsim

**Comment by dcesari** [comment]
Aggiornamento: lavori in corso sul branch medcum, in teoria dal [questo commit](https://github.com/ARPA-SIMC/libsim/commit/1609472268365a40102f578638d965d5dfc93680) dovrebbe funzionare per max/min/med su dati istantanei grigliati.

**Comment by dcesari** [comment]
Lo considero fatto.
