### ISSUE TITLE
dba_qcfilter with --preserve option, all the attributes are stripped

### ISSUE THREAD

**Issue by pat1** [ARPA-SIMC/libsim#81]
the correct behaviour should be to remove attributes involved by QC only
see  https://github.com/ARPA-SIMC/dba_qcfilter/issues/1

**Comment by edigiacomo** [comment]
La tengo aperta nonostante sia inattiva da anni perché dipende da ARPA-SIMC/dba_qcfilter#1.

**Comment by edigiacomo** [comment]
@pat1 @dcesari visto che il comando `dba_qcfilter` della libsim non è più pacchettizzato (#105) ed è stato sostituito da https://github.com/ARPA-SIMC/dba_qcfilter, potrebbe valere la pena dismetterlo direttamente senza stare a tenere sincronizzati i due algoritmi?
