### ISSUE TITLE
[vg6d_transform] average temperature not available

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#82]
```
$ arki-query --data "reftime:=today 0:00;product: GRIB1,80,2,11;level:GRIB1,105,2;" http://arkiope.metarpa:8090/dataset/cosmo_5M_ita > t2m.grib
$ vg6d_transform --comp-stat-proc=0 --comp-step='1 00' --comp-full-steps t2m.grib t_av.grib
[stderr] WARN     vg6d_transform.volgrid6d_class.input_volume-vol1 - no timeranges of the desired statistical processing type 0 available
```
grib file and full debug log of `vg6d_transform` attched

[vg6d.tar.gz](https://github.com/ARPA-SIMC/libsim/files/4402218/vg6d.tar.gz)

**Comment by dcesari** [comment]
At a first glance I would say you need `--comp-stat-proc=254:0` (from instantaneous to average) plus some kind of `--comp-frac-valid=something` but I will look at the data to be sure.

**Comment by dcesari** [comment]
Confirmed. Since these are forecast data you can safely exaggerate with `--comp-frac-valid=0`, otherwise, with observed data, it would be better to use a "safe" value for --comp-frac-valid (see man page).

**Comment by brancomat** [comment]
whoops, my bad, thanks!
