### ISSUE TITLE
conversione variabili ecmwf / cosmo

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/libsim#9]
sarebbe utile (forse) avere un qualche modo di convertire le variabili (tipo da ecmwf a cosmo e viceversa).

questa una lista incompleta di parametri e fattori di conversione:
```
98,128,228 * 1000 = 200,2,61 (pioggia)
98,128,144 * 1000 = 200,2,78 + 200,2,79 (neve)
98,128,186 *  100 = 200,2,73 (copertura nubi basse)
98,128,164 *  100 = 200,2,71 (copertura totale nubi)
98,228,24 + 98,128,129 / 9.8 = 200,201,84 (zero termico¹)
```
¹ Il calcolo dello zero termico è una semplificazione: la `200,201,84` di cosmo-lami usa l'altezza sul livello del mare e un "-999" se l'altezza dello zero termico è inferiore all'orografia, mentre la `98,228,24` di ecmwf è la quota in metri sopra l'orografia che diventa zero se l'altezza dello zero termico è uguale o inferiore all'orografia.
La `98,128,129` è un geopotenziale che (mi dicono) diviso per 9,8 dia l'orografia.
Il procedimento corretto per eventuale implementazione sarebbe fare riferimento ad un ulteriore file grib per l'orografia (`--output-format=grib_api:qualcosa.grb` ?) e poi sommare i singoli valori della `98,228,24` all'orografia in quel punto e mettere a -999 tutti i valori uguali (o inferiori?) all'orografia

**Comment by dcesari** [comment]
On 13/01/2016 14:18, Daniele Branchini wrote:
> sarebbe utile (forse) avere un qualche modo di convertire le variabili
> (tipo da ecmwf a cosmo e viceversa)
>
> questa una lista incompleta di parametri e fattori di conversione:
>
> |98,128,228 * 1000 = 200,2,61 (pioggia)
> 98,128,144 * 1000 = 200,2,78 + 200,2,79 (neve)
> 98,128,186 *  100 = 200,2,73 (copertura nubi basse)
> 98,129,164 *  100 = 200,2,71 (copertura totale nubi)

Queste sono più o meno gestite nell'importazione in gridinfo e nella 
conversione grib-bufr-grib, per cui credo che una vg6d_transform che fa 
trasformazione vuota su un grib ECMWF e riesporta con un template che 
abbia tabella 2 versione 2 e centro != 98 potrebbe uscire rinormalizzato.

> 98,228,24 + 98,128,129 / 98 = 200,201,84 (zero termico¹)

qui mi è venuto ora in mente che, a parte il tuo programma python, si 
potrebbe definire una funzione in alchimia che somma l'orografia.

**Comment by dcesari** [comment]
> |98,128,228 * 1000 = 200,2,61 (pioggia)
> 98,128,186 *  100 = 200,2,73 (copertura nubi basse)
> 98,128,164 *  100 = 200,2,71 (copertura totale nubi)

Queste ora sono tutte gestite (comprese anche nubi medie e alte, umidità del suolo e altri tipi di prec.), vengono rinormalizzate alla corrispondenti variabili WMO o estensioni locali SIMC se si imposta un template con centro non 98, meglio 200 in uscita alla vg6d_transform

> 98,128,144 * 1000 = 200,2,78 + 200,2,79 (neve)

Per gestire questa bisogna fare l'operazione di cui sopra ai dati ECMWF mentre per COSMO bisogna fare un giro con alchimia, `--output-variable-list=B13205` che fa il calcolo di cui sopra (già implementato)

> 98,228,24 + 98,128,129 / 98 = 200,201,84 (zero termico)

Date le caratteristiche del nostro fantastico data model e l'inventiva di ECMWF, non si riesce a fare niente di pulito in questo caso. Soprassiedo e chiudo.
