### ISSUE TITLE
Remove some dependencies from BuildRequires

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/libsim#90]
If I understand correctly, the following `BuildRequires` are not direct dependencies and they can be safely removed:

- `jasper-devel` (required by `eccodes-devel`)
- `libpng-devel` (required by `eccodes-devel`)
- `cairo-devel` (required by `ncl-devel`)

**Comment by dcesari** [comment]
In principle I agree, but moncic said no: https://simc.arpae.it/moncic-ci/libsim/202202080820/master/centos7/build.log, we probably need to erase -lcairo somewhere else, maybe in che configure.ac

**Comment by edigiacomo** [comment]
I'm sorry, It Worked On My Computer™ :grimacing: ... Yesterday I tested only Rocky Linux 8, but in CentOS 7 `ncl-devel` doesn't require `cairo-devel` nor `png-devel`

```
[edigiacomo@rocky8 ~]$ rpm -qR ncl-devel | grep cairo
cairo-devel
[edigiacomo@sette ~]$ rpm -qR ncl-devel | grep cairo
```

Let's see if I fixed the issue in commit 823feb0 :crossed_fingers:

**Comment by dcesari** [comment]
Stavo provando la stessa cosa :-)

**Comment by edigiacomo** [comment]
Fixed https://simc.arpae.it/moncic-ci/libsim/last/master/centos7/build.log
